### ISSUE TITLE
章「こんな勉強会があるよ！」 - もくもく執筆会編

### ISSUE THREAD

**Issue by llminatoll** [onestop-techbook/Onestop-meeting#8]
熊谷さん、湊川でもくもく執筆会の紹介記事を寄稿します。

## 親方さんからもらった項目例

・会/コミュニティの概要、活動履歴
・立ち上げの経緯
・大事にしていること
・やってよかったこと
・これから勉強会に参加、登壇、主催（どれかでもいいです）する人に向けてのメッセージ

**Comment by llminatoll** [comment]
親方さんからもらった項目例がテンプレートになるのかな？ 
これに沿って書いていくという理解ですがあってます？( ´ ▽ ` ) @oyakata2438

**Comment by llminatoll** [comment]
章一覧
https://github.com/onestop-techbook/Onestop-meeting/blob/master/articles/catalog.yml

**Comment by llminatoll** [comment]
.reファイル作りました。 #9

**Comment by llminatoll** [comment]
親方さんより

> テンプレは絶対的なものではないので、まあ参考に書いてくださいな、かな。他に何かあったほうがいい項目あれば教えてくださいな

とのことでした！

**Comment by es-kumagai** [comment]
湊川さん、ありがとうございます！(・◇・)ゞ

**Comment by es-kumagai** [comment]
第14章の節に綴る内容を想像してみようとしたのですけど、全体を通して『なぜ 14 章が存在するのか』を打ち出さないとふわふわしますね。まずそこを、全体の構成を眺めつつイメージしてみますね。

**Comment by es-kumagai** [comment]
誰に向けての紹介にするかを定めようと思ったのですけど、主題が「勉強会の全てを網羅」なのもあってか難しいですね。とりあえず **ざっくり決めて書き始めて、本編の構成が整うに従って軌道修正していく** 感じが良さそうに思えてきました。

### 照準を絞りたい

それでも、どこに視線を向けるかは定めておきたい気がするのですけど、

1. 万人が対象なら焦点を絞らないで **一般的な紹介** 、そしてメッセージだけ焦点を絞るか。
2. それとも、**これから参加・これから主催するどちらか目線**（登壇はうちはない）に絞って綴るか。
3. 親方さんからの **インタビュー** と受け止めて綴るか。

などなど、どこに目線を向けると内容が整うだろう。最終的には微々たる違いになるとは思うのですけど。

### 所感

#### 1. 万人を対象

万人を対象にした場合、内容は基本的に、まさしく「こんな勉強会があるよ」というパンフレット的、APPENDIX 的なものになるように感じます。たとえるなら『技術書典にサークル参加で現地へ行ったら椅子の上にチラシが置いてあった』みたいなイメージでしょうか。

この方針は「これから参加する人」に向けたイメージとも近いかもしれません。あと、話をいただいた「もくもく執筆会の紹介記事を書いて欲しい」という **要望にいちばんシンプルにそぐう** ものとは思います。

#### 2. これから、参加または主催する人を対象

もし **これから参加する人をイメージした場合は (1.) に近くなる** ように感じます。文面が「だから来ようよ！」みたいなテイストに寄っていくと思いますけれど。

もし **これから主催する人を対象にした場合** は、懸念する事項の色が変わってきそうな気がします。たとえば「〜が不安だったけど、こんな風にしてみたら、どうだった」みたいな話になる、とか。

#### 3. インタビューと捉える

登場人物は想定しないにしても、話をいただいた時の項目を、インタビュアーが訪ねてきたと思って、その時感じたことを綴ってみるくらいの姿勢で綴るとか。本のメインテーマが広くてふわふわしているので、ここもそうした方が **全体になじむかも** しれない？

それぞれの項に対して、基本２人で１段落ずつ、合計２段落ずつ、ふわっと **思い浮かんだことを綴るかたちもアリ** な気がしてきました。

**Comment by oyakata2438** [comment]
もやっとした状態で話を持っていったので、申し訳ないところです・・・
　（私自身も確定した方針を持ってるわけではないので・・・すみません。

悩んでらっしゃるところはもっともだと思います。悩ましいですね・・・

あくまで一案として、
照準を絞りたい、については、
・巻末にAppendix=アンケートとして、新規参加者（万人）に向けて、ある程度テンプレ準拠でチラシ的に。
・本文に、主催ノウハウとして、成立に至った経緯や開催ノウハウ、その他、ある程度テクニカルな部分も含んで、勉強会主催者にむけて書く。

の二本立て、というのはどうでしょう？

現14章は、やっぱりチラシ的というか、あまり深掘りする感じではないのです。

一方で、勉強会を開催する人にとっては、人が定着する勉強会ってどういう工夫なり主催者の思考なりがあるんだろう？というところは絶対知りたいところだし、会場の探し方とか、イベントの流れについても知りたいところです。

と思いましたが、どうでしょう？

**Comment by es-kumagai** [comment]
ありがとうございます。なんとなくイメージが浮かんできました。そうしましたら、まずは１４章を万人向けのアプローチで完成させるのが良いかもですね。

そうしているうちに本編も整ってきて、本編に書き加えたいことも浮かんできそうな気がしてきました。もちろん湊川さんのイメージが膨らんでいれば、本編も並行していけるかもですけれど。

**Comment by es-kumagai** [comment]
@llminatoll さん。ひとまず「別冊 もくもく執筆会」から使えそうなものをピックアップして、今回の原稿内に記載してみました。今のところ、別のブランチ ``various-techbook_meetup`` に変更をコミットしてあります。

前後のつながりや言い回しなど、細かい部分の整合性は無視して記載してありますので、ここからざくざく書き換えていけたらいいかなって思ってます。詳しくはまた打ち合わせのときにお話ししましょう。

**Comment by llminatoll** [comment]
@es-kumagai さん
早速、ありがとうございます！
ちょうど、別冊の冊子と共通するところがありそうだと考えておりました。
はい、打ち合わせのときにまた擦り合わせましょう！

**Comment by llminatoll** [comment]
#25 加筆しました〜！

**Comment by llminatoll** [comment]
ある程度整ったので、クローズしますね！
